# test of JSRR

    PUTS TEST_MSG:
    PUTS START_MSG:
    PUTS SPACES:

    LEA R1,SUB_ROUTINE:
    JSRR R1
    PUTS RETURN_FROM_SUBROUTINE:

END_TESTS: NOP
    PUTS SPACES:
    PUTS END_MSG:
    HALT

SUB_ROUTINE: NOP
   PUTS IN_SUBROUTINE:
   PUTS PASSED:
   RET

# print messages 

START_MSG: DC "START"
END_MSG: DC "END"

FAILED: DC "_____FAILED"
PASSED: DC "_____PASSED"
SPACES: DC "--------------"

IN_SUBROUTINE: DC "IN_SUBROUTINE"
RETURN_FROM_SUBROUTINE: DC "RETURNED_FROM_SUBROUTINE"

TEST_MSG: DC "TEST_JSRR"